### ISSUE TITLE
Instructions for running batch file for TeaVM

### ISSUE THREAD

**Issue by jontyman** [keinhaar/gwtswing#11]
Am currently using Java 11
Ran command:
nobuto.bat -t installToMaven -vvv

Get following output:
mkdir build\classes

java -Djavax.net.ssl.trustStoreType=WINDOWS-ROOT -Djava.net.useSystemProxies=true -cp build/classes;build/nobuto.jar de.exware.nobuto.Main $1 $2 $3 $4
JAVA Version: 11.0.21
Operating System: Windows 10 10.0 amd64
Trying default: build\Build.java
Compile Builder Class
Executing target 'dist' in Class 'Build'
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at de.exware.nobuto.Main.main(Main.java:69)
Caused by: java.net.UnknownHostException: C
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:1062)
        at java.base/sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:1024)
        at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1119)
        at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1105)
        at java.base/sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:312)
        at java.base/sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:418)
        at java.base/java.net.URL.openStream(URL.java:1165)
        at de.exware.nobuto.maven.Maven.get(Maven.java:64)
        at de.exware.nobuto.maven.MavenDependency.addToClasspath(MavenDependency.java:26)
        at de.exware.nobuto.java.JavaBuilder.compile(JavaBuilder.java:96)
        at Build.compile(Build.java:62)
        at de.exware.nobuto.Builder.dist(Builder.java:68)
        at Build.dist(Build.java:26)
        ... 5 more

**Comment by keinhaar** [comment]
This is a problem on windows only. I've updated the build and it now works for me. please update all 3 projects and rebuild all of them in this order gplatform, gplatform-teavm, gwtswing
Depending on your windows version you may need to remove the parameter "-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT" from the nobuto.bat file if you get an certificate validation error.
Also you may need to run the command twice, if the first run fails. This is caused by the changes to the build.
Please give feedback how it worked.

**Comment by jontyman** [comment]
gplatform and gplatform.teavm seem to install.
GWTSwing does not seem to install

I get the following:
```
java -Djavax.net.ssl.trustStoreType=WINDOWS-ROOT -Djava.net.useSystemProxies=true -cp build/classes;build/nobuto.jar de.exware.nobuto.Main $1 $2 $3 $4
JAVA Version: 11.0.21
Operating System: Windows 10 10.0 amd64
Trying default: build\Build.java
Compile Builder Class
Executing target 'dist' in Class 'Build'
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at de.exware.nobuto.Main.main(Main.java:69)
Caused by: java.net.UnknownHostException: C
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:1062)
        at java.base/sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:1024)
        at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1119)
        at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1105)
        at java.base/sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:312)
        at java.base/sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:418)
        at java.base/java.net.URL.openStream(URL.java:1165)
        at de.exware.nobuto.maven.Maven.get(Maven.java:64)
        at de.exware.nobuto.maven.MavenDependency.addToClasspath(MavenDependency.java:26)
        at de.exware.nobuto.java.JavaBuilder.compile(JavaBuilder.java:96)
        at Build.compile(Build.java:62)
        at de.exware.nobuto.Builder.dist(Builder.java:68)
        at Build.dist(Build.java:26)
        ... 5 more
```

Running without the parameter "-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT" does not seem to make a difference
```
java -Djava.net.useSystemProxies=true -cp build/classes;build/nobuto.jar de.exware.nobuto.Main $1 $2 $3 $4
JAVA Version: 11.0.21
Operating System: Windows 10 10.0 amd64
Trying default: build\Build.java
Compile Builder Class
Executing target 'dist' in Class 'Build'
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at de.exware.nobuto.Main.main(Main.java:69)
Caused by: java.net.UnknownHostException: C
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:229)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:1062)
        at java.base/sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:1024)
        at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1119)
        at java.base/sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1105)
        at java.base/sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:312)
        at java.base/sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:418)
        at java.base/java.net.URL.openStream(URL.java:1165)
        at de.exware.nobuto.maven.Maven.get(Maven.java:64)
        at de.exware.nobuto.maven.MavenDependency.addToClasspath(MavenDependency.java:26)
        at de.exware.nobuto.java.JavaBuilder.compile(JavaBuilder.java:96)
        at Build.compile(Build.java:62)
        at de.exware.nobuto.Builder.dist(Builder.java:68)
        at Build.dist(Build.java:26)
        ... 5 more
```

**Comment by keinhaar** [comment]
Sorry, my fault. I did not realize, that my last push did not work.
I've fixed that and double checked the build with the downloaded source from here.

Please try again, and: try 2 times if you get this error.

`Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at de.exware.nobuto.Main.main(Main.java:68)
Caused by: java.lang.NoSuchMethodError: 'void de.exware.nobuto.java.JavaBuilder.<init>(java.lang.String)'
        at Build.<init>(Build.java:19)
        ... 5 more`

**Comment by jontyman** [comment]
Thanks. I've tried the batch file now and GWTSwing is installing.
